name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: fixup permissions
        run: chown -R 1000:1000 .

      - name: build
        image: ghcr.io/manufactureduson/mds-builder:latest 
        options: --user build
        run: make build MACHINE=network_player
