name: CI
on:
  push:
    branches: [ main ]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: fixup permissions
        run: chown -R 1000:1000 .

  build: 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/manufactureduson/mds-builder:latest 
      options: --user build
    steps:
      - name: build
        run: make build MACHINE=network_player
