name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/manufactureduson/mds-builder:latest 
      options: --user build
      
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/mds-builder/mds-builder

      - name: Checkout code
        uses: actions/checkout@v4

      - name: build
        run: make build MACHINE=network_player
